// Central badge and achievement seed data for NodeWeave.
export const BADGE_CATALOG = [
  {
    "id": "badge_ach_001",
    "name": "初来乍到",
    "description": "注册后自动获得",
    "icon": "◈",
    "color": "#00f0ff",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_002",
    "name": "七日连签",
    "description": "连续签到7天",
    "icon": "🔥",
    "color": "#ff8c00",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_003",
    "name": "三十日连签",
    "description": "连续签到30天",
    "icon": "💎",
    "color": "#ffd700",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_004",
    "name": "首帖纪念",
    "description": "发布第一篇帖子",
    "icon": "✍️",
    "color": "#7fff00",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_005",
    "name": "百帖宗师",
    "description": "累计发布100篇帖子",
    "icon": "📝",
    "color": "#9d00ff",
    "rarity": "epic",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_006",
    "name": "千帖传说",
    "description": "累计发布1000篇帖子",
    "icon": "👑",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_007",
    "name": "首赞达人",
    "description": "获得第一个赞",
    "icon": "⭐",
    "color": "#ffd700",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_008",
    "name": "百赞收割",
    "description": "累计获100个赞",
    "icon": "🌟",
    "color": "#ff8c00",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_009",
    "name": "千赞之星",
    "description": "累计获1000个赞",
    "icon": "💫",
    "color": "#9d00ff",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_010",
    "name": "万赞传奇",
    "description": "累计获10000个赞",
    "icon": "🏆",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_011",
    "name": "沙发之王",
    "description": "首次抢到帖子沙发",
    "icon": "🛋️",
    "color": "#00f0ff",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_012",
    "name": "评论新星",
    "description": "发表第1条评论",
    "icon": "💬",
    "color": "#7fff00",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_013",
    "name": "????",
    "description": "累计评论500条",
    "icon": "🗣️",
    "color": "#ff003c",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_014",
    "name": "最佳答案",
    "description": "回答被采纳1次",
    "icon": "✅",
    "color": "#ffd700",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_015",
    "name": "答疑专家",
    "description": "回答被采纳10次",
    "icon": "🎓",
    "color": "#9d00ff",
    "rarity": "epic",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_016",
    "name": "悬赏猎人",
    "description": "回答被采纳且获得悬赏",
    "icon": "🎯",
    "color": "#ff8c00",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_017",
    "name": "关注破百",
    "description": "获得100位粉丝",
    "icon": "👥",
    "color": "#00f0ff",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_018",
    "name": "万人迷",
    "description": "获得10000位粉丝",
    "icon": "💝",
    "color": "#ff003c",
    "rarity": "legendary",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_019",
    "name": "完美档案",
    "description": "完善所有个人资料",
    "icon": "📋",
    "color": "#7fff00",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_020",
    "name": "实名先锋",
    "description": "完成实名认证",
    "icon": "🛡️",
    "color": "#00f0ff",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_021",
    "name": "永久居民",
    "description": "注册满365天",
    "icon": "🏠",
    "color": "#ffd700",
    "rarity": "epic",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_022",
    "name": "三朝元老",
    "description": "注册满3年",
    "icon": "🏰",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_023",
    "name": "深夜活跃",
    "description": "凌晨2-5点发帖5次",
    "icon": "🦉",
    "color": "#9d00ff",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_024",
    "name": "早起鸟儿",
    "description": "连续30天6-8点签到",
    "icon": "🌅",
    "color": "#ff8c00",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_025",
    "name": "博客达人",
    "description": "发布10篇博客",
    "icon": "📖",
    "color": "#9d00ff",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_026",
    "name": "打赏新贵",
    "description": "首次被打赏",
    "icon": "💰",
    "color": "#ffd700",
    "rarity": "common",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_027",
    "name": "财源广进",
    "description": "累计被打赏10000币",
    "icon": "💸",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_028",
    "name": "慷慨解囊",
    "description": "累计打赏别人5000币",
    "icon": "🤲",
    "color": "#ff8c00",
    "rarity": "epic",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_029",
    "name": "五星好评",
    "description": "获得5次满分评分",
    "icon": "★★★★★",
    "color": "#ffd700",
    "rarity": "rare",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_ach_030",
    "name": "举报卫士",
    "description": "有效举报5次被采纳",
    "icon": "🚨",
    "color": "#ff003c",
    "rarity": "uncommon",
    "category": "achievement",
    "price": 0,
    "is_special": 1,
    "quantity": -1
  },
  {
    "id": "badge_gen_01",
    "name": "霓虹之心",
    "description": "赛博朋克风格的爱心徽章",
    "icon": "💜",
    "color": "#ff003c",
    "rarity": "uncommon",
    "category": "general",
    "price": 50,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_gen_02",
    "name": "数字幽灵",
    "description": "代码世界的游荡者",
    "icon": "👻",
    "color": "#00f0ff",
    "rarity": "uncommon",
    "category": "general",
    "price": 80,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_gen_03",
    "name": "像素方块",
    "description": "8-bit复古像素风",
    "icon": "🟩",
    "color": "#7fff00",
    "rarity": "common",
    "category": "general",
    "price": 30,
    "is_special": 0,
    "quantity": -1
  },
  {
    "id": "badge_gen_04",
    "name": "赛博之眼",
    "description": "洞察一切的电子眼",
    "icon": "👁️",
    "color": "#ff003c",
    "rarity": "rare",
    "category": "general",
    "price": 200,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_gen_05",
    "name": "矩阵雨滴",
    "description": "致敬黑客帝国",
    "icon": "💧",
    "color": "#00f0ff",
    "rarity": "rare",
    "category": "general",
    "price": 180,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_gen_06",
    "name": "太空漫游",
    "description": "探索无尽宇宙",
    "icon": "🚀",
    "color": "#9d00ff",
    "rarity": "epic",
    "category": "general",
    "price": 500,
    "is_special": 0,
    "quantity": 300
  },
  {
    "id": "badge_gen_07",
    "name": "雷霆之怒",
    "description": "闪电般的力量",
    "icon": "⚡",
    "color": "#ffd700",
    "rarity": "epic",
    "category": "general",
    "price": 450,
    "is_special": 0,
    "quantity": 300
  },
  {
    "id": "badge_gen_08",
    "name": "凤凰涅槃",
    "description": "浴火重生的传奇",
    "icon": "🐦‍🔥",
    "color": "#ff8c00",
    "rarity": "legendary",
    "category": "general",
    "price": 1500,
    "is_special": 0,
    "quantity": 100
  },
  {
    "id": "badge_gen_09",
    "name": "极光之舞",
    "description": "北极光的绚丽色彩",
    "icon": "🌌",
    "color": "#9d00ff",
    "rarity": "legendary",
    "category": "general",
    "price": 1200,
    "is_special": 0,
    "quantity": 100
  },
  {
    "id": "badge_gen_10",
    "name": "幸运四叶",
    "description": "带来好运的幸运草",
    "icon": "🍀",
    "color": "#7fff00",
    "rarity": "common",
    "category": "general",
    "price": 40,
    "is_special": 0,
    "quantity": -1
  },
  {
    "id": "badge_tech_01",
    "name": "Python之蛇",
    "description": "Python语言爱好者",
    "icon": "🐍",
    "color": "#7fff00",
    "rarity": "uncommon",
    "category": "tech",
    "price": 60,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_tech_02",
    "name": "Rust铁锈",
    "description": "Rust语言信仰者",
    "icon": "⚙️",
    "color": "#ff8c00",
    "rarity": "rare",
    "category": "tech",
    "price": 150,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_tech_03",
    "name": "JS忍者",
    "description": "JavaScript高手",
    "icon": "🥷",
    "color": "#ffd700",
    "rarity": "rare",
    "category": "tech",
    "price": 160,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_tech_04",
    "name": "Go地鼠",
    "description": "Go语言玩家",
    "icon": "🐹",
    "color": "#00f0ff",
    "rarity": "uncommon",
    "category": "tech",
    "price": 70,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_tech_05",
    "name": "Docker鲸鱼",
    "description": "容器化大师",
    "icon": "🐳",
    "color": "#00f0ff",
    "rarity": "rare",
    "category": "tech",
    "price": 200,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_tech_06",
    "name": "K8s舵手",
    "description": "Kubernetes掌控者",
    "icon": "☸️",
    "color": "#9d00ff",
    "rarity": "epic",
    "category": "tech",
    "price": 600,
    "is_special": 0,
    "quantity": 300
  },
  {
    "id": "badge_tech_07",
    "name": "Git猫头鹰",
    "description": "版本控制专家",
    "icon": "🦉",
    "color": "#ff8c00",
    "rarity": "uncommon",
    "category": "tech",
    "price": 90,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_tech_08",
    "name": "AI驯兽师",
    "description": "大语言模型玩家",
    "icon": "🤖",
    "color": "#ffd700",
    "rarity": "epic",
    "category": "tech",
    "price": 800,
    "is_special": 0,
    "quantity": 200
  },
  {
    "id": "badge_tech_09",
    "name": "安全锁匠",
    "description": "网络安全守护者",
    "icon": "🔐",
    "color": "#ff003c",
    "rarity": "rare",
    "category": "tech",
    "price": 250,
    "is_special": 0,
    "quantity": 400
  },
  {
    "id": "badge_tech_10",
    "name": "Linux企鹅",
    "description": "开源系统信仰",
    "icon": "🐧",
    "color": "#7fff00",
    "rarity": "uncommon",
    "category": "tech",
    "price": 55,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_tech_11",
    "name": "数据库龙",
    "description": "SQL与NoSQL大师",
    "icon": "🐉",
    "color": "#9d00ff",
    "rarity": "epic",
    "category": "tech",
    "price": 550,
    "is_special": 0,
    "quantity": 300
  },
  {
    "id": "badge_tech_12",
    "name": "全栈独角兽",
    "description": "前后端通吃",
    "icon": "🦄",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "tech",
    "price": 2000,
    "is_special": 0,
    "quantity": 50
  },
  {
    "id": "badge_soc_01",
    "name": "点赞狂魔",
    "description": "送出1000个赞后解锁购买",
    "icon": "❤️",
    "color": "#ff003c",
    "rarity": "uncommon",
    "category": "social",
    "price": 100,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_soc_02",
    "name": "沙发猎人",
    "description": "抢沙发专用",
    "icon": "🎯",
    "color": "#ffd700",
    "rarity": "common",
    "category": "social",
    "price": 35,
    "is_special": 0,
    "quantity": -1
  },
  {
    "id": "badge_soc_03",
    "name": "段子手",
    "description": "幽默风趣的灵魂",
    "icon": "😄",
    "color": "#7fff00",
    "rarity": "uncommon",
    "category": "social",
    "price": 75,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_soc_04",
    "name": "和平使者",
    "description": "化解冲突的调解者",
    "icon": "🕊️",
    "color": "#00f0ff",
    "rarity": "rare",
    "category": "social",
    "price": 220,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_soc_05",
    "name": "社交蝴蝶",
    "description": "人脉广泛",
    "icon": "🦋",
    "color": "#9d00ff",
    "rarity": "rare",
    "category": "social",
    "price": 280,
    "is_special": 0,
    "quantity": 400
  },
  {
    "id": "badge_soc_06",
    "name": "派对达人",
    "description": "社区活跃分子",
    "icon": "🎉",
    "color": "#ff8c00",
    "rarity": "uncommon",
    "category": "social",
    "price": 65,
    "is_special": 0,
    "quantity": 999
  },
  {
    "id": "badge_soc_07",
    "name": "知心伙伴",
    "description": "倾听者与支持者",
    "icon": "🤗",
    "color": "#ff003c",
    "rarity": "rare",
    "category": "social",
    "price": 190,
    "is_special": 0,
    "quantity": 500
  },
  {
    "id": "badge_soc_08",
    "name": "锦鲤附体",
    "description": "好运连连",
    "icon": "🎏",
    "color": "#ffd700",
    "rarity": "epic",
    "category": "social",
    "price": 680,
    "is_special": 0,
    "quantity": 200
  },
  {
    "id": "badge_spc_01",
    "name": "新年快乐",
    "description": "2026新年限定",
    "icon": "🧧",
    "color": "#ff003c",
    "rarity": "legendary",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 500
  },
  {
    "id": "badge_spc_02",
    "name": "中秋团圆",
    "description": "中秋限定徽章",
    "icon": "🥮",
    "color": "#ffd700",
    "rarity": "epic",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 500
  },
  {
    "id": "badge_spc_04",
    "name": "万圣惊魂",
    "description": "万圣节限定",
    "icon": "🎃",
    "color": "#ff8c00",
    "rarity": "rare",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 500
  },
  {
    "id": "badge_spc_05",
    "name": "圣诞老人",
    "description": "圣诞节限定",
    "icon": "🎅",
    "color": "#ff003c",
    "rarity": "rare",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 500
  },
  {
    "id": "badge_spc_08",
    "name": "周年庆",
    "description": "NodeWeave周年限定",
    "icon": "🎂",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 100
  },
  {
    "id": "badge_spc_09",
    "name": "内测先锋",
    "description": "内测期间活跃用户",
    "icon": "🔬",
    "color": "#9d00ff",
    "rarity": "legendary",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 200
  },
  {
    "id": "badge_spc_10",
    "name": "Bug猎人",
    "description": "发现并提交有效Bug",
    "icon": "🐛",
    "color": "#ffd700",
    "rarity": "legendary",
    "category": "special",
    "price": 0,
    "is_special": 1,
    "quantity": 50
  },
  {
    "id": "badge_rep_01",
    "name": "青铜勋章",
    "description": "声望100解锁",
    "icon": "🥉",
    "color": "#cd7f32",
    "rarity": "common",
    "category": "general",
    "price": 100,
    "is_special": 0,
    "quantity": -1
  },
  {
    "id": "badge_rep_02",
    "name": "白银勋章",
    "description": "声望500解锁",
    "icon": "🥈",
    "color": "#c0c0c0",
    "rarity": "uncommon",
    "category": "general",
    "price": 250,
    "is_special": 0,
    "quantity": -1
  },
  {
    "id": "badge_rep_03",
    "name": "黄金勋章",
    "description": "声望2000解锁",
    "icon": "🥇",
    "color": "#ffd700",
    "rarity": "rare",
    "category": "general",
    "price": 500,
    "is_special": 0,
    "quantity": -1
  }
];

export const ACHIEVEMENT_CATALOG = [
  {
    "id": "ach_newcomer",
    "name": "初来乍到",
    "description": "?????????",
    "icon": "◈",
    "category": "achievement",
    "condition_type": "account_exists",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_001",
    "coin_reward": 10,
    "condition_label": "?????????"
  },
  {
    "id": "ach_signin_7",
    "name": "七日连签",
    "description": "???? 7 ?",
    "icon": "🔥",
    "category": "achievement",
    "condition_type": "signin_streak",
    "condition_value": 7,
    "badge_reward_id": "badge_ach_002",
    "coin_reward": 30,
    "condition_label": "???? 7 ?"
  },
  {
    "id": "ach_signin_30",
    "name": "三十日连签",
    "description": "???? 30 ?",
    "icon": "💎",
    "category": "achievement",
    "condition_type": "signin_streak",
    "condition_value": 30,
    "badge_reward_id": "badge_ach_003",
    "coin_reward": 100,
    "condition_label": "???? 30 ?"
  },
  {
    "id": "ach_first_post",
    "name": "首帖纪念",
    "description": "??? 1 ???",
    "icon": "✍️",
    "category": "achievement",
    "condition_type": "post_count",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_004",
    "coin_reward": 10,
    "condition_label": "??? 1 ???"
  },
  {
    "id": "ach_100_posts",
    "name": "百帖宗师",
    "description": "???? 100 ???",
    "icon": "📝",
    "category": "achievement",
    "condition_type": "post_count",
    "condition_value": 100,
    "badge_reward_id": "badge_ach_005",
    "coin_reward": 200,
    "condition_label": "???? 100 ???"
  },
  {
    "id": "ach_1000_posts",
    "name": "千帖传说",
    "description": "???? 1000 ???",
    "icon": "👑",
    "category": "achievement",
    "condition_type": "post_count",
    "condition_value": 1000,
    "badge_reward_id": "badge_ach_006",
    "coin_reward": 1000,
    "condition_label": "???? 1000 ???"
  },
  {
    "id": "ach_first_like",
    "name": "首赞达人",
    "description": "???????? 1 ??",
    "icon": "⭐",
    "category": "achievement",
    "condition_type": "received_likes",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_007",
    "coin_reward": 10,
    "condition_label": "???????? 1 ??"
  },
  {
    "id": "ach_100_likes",
    "name": "百赞收割",
    "description": "???? 100 ??",
    "icon": "🌟",
    "category": "achievement",
    "condition_type": "received_likes",
    "condition_value": 100,
    "badge_reward_id": "badge_ach_008",
    "coin_reward": 100,
    "condition_label": "???? 100 ??"
  },
  {
    "id": "ach_1000_likes",
    "name": "千赞之星",
    "description": "???? 1000 ??",
    "icon": "💫",
    "category": "achievement",
    "condition_type": "received_likes",
    "condition_value": 1000,
    "badge_reward_id": "badge_ach_009",
    "coin_reward": 500,
    "condition_label": "???? 1000 ??"
  },
  {
    "id": "ach_10000_likes",
    "name": "万赞传奇",
    "description": "???? 10000 ??",
    "icon": "🏆",
    "category": "achievement",
    "condition_type": "received_likes",
    "condition_value": 10000,
    "badge_reward_id": "badge_ach_010",
    "coin_reward": 3000,
    "condition_label": "???? 10000 ??"
  },
  {
    "id": "ach_first_floor",
    "name": "沙发之王",
    "description": "????????",
    "icon": "🛋️",
    "category": "achievement",
    "condition_type": "first_floor_count",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_011",
    "coin_reward": 20,
    "condition_label": "????????"
  },
  {
    "id": "ach_first_comment",
    "name": "评论新星",
    "description": "??? 1 ???",
    "icon": "💬",
    "category": "achievement",
    "condition_type": "comment_count",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_012",
    "coin_reward": 5,
    "condition_label": "??? 1 ???"
  },
  {
    "id": "ach_500_comments",
    "name": "????",
    "description": "???? 500 ???",
    "icon": "🗣️",
    "category": "achievement",
    "condition_type": "comment_count",
    "condition_value": 500,
    "badge_reward_id": "badge_ach_013",
    "coin_reward": 200,
    "condition_label": "???? 500 ???"
  },
  {
    "id": "ach_first_accepted",
    "name": "最佳答案",
    "description": "????? 1 ?",
    "icon": "✅",
    "category": "achievement",
    "condition_type": "accepted_answers",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_014",
    "coin_reward": 50,
    "condition_label": "????? 1 ?"
  },
  {
    "id": "ach_10_accepted",
    "name": "答疑专家",
    "description": "????? 10 ?",
    "icon": "🎓",
    "category": "achievement",
    "condition_type": "accepted_answers",
    "condition_value": 10,
    "badge_reward_id": "badge_ach_015",
    "coin_reward": 300,
    "condition_label": "????? 10 ?"
  },
  {
    "id": "ach_bounty_hunter",
    "name": "悬赏猎人",
    "description": "??????????",
    "icon": "🎯",
    "category": "achievement",
    "condition_type": "bounty_accepted",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_016",
    "coin_reward": 80,
    "condition_label": "??????????"
  },
  {
    "id": "ach_100_followers",
    "name": "关注破百",
    "description": "?? 100 ???",
    "icon": "👥",
    "category": "achievement",
    "condition_type": "followers_count",
    "condition_value": 100,
    "badge_reward_id": "badge_ach_017",
    "coin_reward": 300,
    "condition_label": "?? 100 ???"
  },
  {
    "id": "ach_10000_followers",
    "name": "万人迷",
    "description": "?? 10000 ???",
    "icon": "💝",
    "category": "achievement",
    "condition_type": "followers_count",
    "condition_value": 10000,
    "badge_reward_id": "badge_ach_018",
    "coin_reward": 5000,
    "condition_label": "?? 10000 ???"
  },
  {
    "id": "ach_profile_complete",
    "name": "完美档案",
    "description": "??????",
    "icon": "📋",
    "category": "achievement",
    "condition_type": "profile_complete",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_019",
    "coin_reward": 20,
    "condition_label": "??????"
  },
  {
    "id": "ach_verified",
    "name": "实名先锋",
    "description": "????/????",
    "icon": "🛡️",
    "category": "achievement",
    "condition_type": "real_name_verified",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_020",
    "coin_reward": 30,
    "condition_label": "????/????"
  },
  {
    "id": "ach_account_365",
    "name": "永久居民",
    "description": "??? 365 ?",
    "icon": "🏠",
    "category": "achievement",
    "condition_type": "account_age_days",
    "condition_value": 365,
    "badge_reward_id": "badge_ach_021",
    "coin_reward": 365,
    "condition_label": "??? 365 ?"
  },
  {
    "id": "ach_account_1095",
    "name": "三朝元老",
    "description": "??? 3 ?",
    "icon": "🏰",
    "category": "achievement",
    "condition_type": "account_age_days",
    "condition_value": 1095,
    "badge_reward_id": "badge_ach_022",
    "coin_reward": 1095,
    "condition_label": "??? 3 ?"
  },
  {
    "id": "ach_night_posts",
    "name": "深夜活跃",
    "description": "?? 2-5 ??? 5 ?",
    "icon": "🦉",
    "category": "achievement",
    "condition_type": "night_post_count",
    "condition_value": 5,
    "badge_reward_id": "badge_ach_023",
    "coin_reward": 50,
    "condition_label": "?? 2-5 ??? 5 ?"
  },
  {
    "id": "ach_early_signin",
    "name": "早起鸟儿",
    "description": "6-8 ????? 30 ?",
    "icon": "🌅",
    "category": "achievement",
    "condition_type": "early_signin_count",
    "condition_value": 30,
    "badge_reward_id": "badge_ach_024",
    "coin_reward": 120,
    "condition_label": "6-8 ????? 30 ?"
  },
  {
    "id": "ach_10_blogs",
    "name": "博客达人",
    "description": "?? 10 ???",
    "icon": "📖",
    "category": "achievement",
    "condition_type": "blog_count",
    "condition_value": 10,
    "badge_reward_id": "badge_ach_025",
    "coin_reward": 150,
    "condition_label": "?? 10 ???"
  },
  {
    "id": "ach_first_tip_received",
    "name": "打赏新贵",
    "description": "??????",
    "icon": "💰",
    "category": "achievement",
    "condition_type": "tips_received_total",
    "condition_value": 1,
    "badge_reward_id": "badge_ach_026",
    "coin_reward": 20,
    "condition_label": "??????"
  },
  {
    "id": "ach_10000_tip_received",
    "name": "财源广进",
    "description": "???? 10000 ?????",
    "icon": "💸",
    "category": "achievement",
    "condition_type": "tips_received_total",
    "condition_value": 10000,
    "badge_reward_id": "badge_ach_027",
    "coin_reward": 2000,
    "condition_label": "???? 10000 ?????"
  },
  {
    "id": "ach_5000_tip_sent",
    "name": "慷慨解囊",
    "description": "?????? 5000 ???",
    "icon": "🤲",
    "category": "achievement",
    "condition_type": "tips_sent_total",
    "condition_value": 5000,
    "badge_reward_id": "badge_ach_028",
    "coin_reward": 600,
    "condition_label": "?????? 5000 ???"
  },
  {
    "id": "ach_5_five_star",
    "name": "五星好评",
    "description": "?? 5 ?????",
    "icon": "★★★★★",
    "category": "achievement",
    "condition_type": "five_star_ratings_received",
    "condition_value": 5,
    "badge_reward_id": "badge_ach_029",
    "coin_reward": 100,
    "condition_label": "?? 5 ?????"
  },
  {
    "id": "ach_5_reports",
    "name": "举报卫士",
    "description": "??????? 5 ?",
    "icon": "🚨",
    "category": "achievement",
    "condition_type": "accepted_reports",
    "condition_value": 5,
    "badge_reward_id": "badge_ach_030",
    "coin_reward": 80,
    "condition_label": "??????? 5 ?"
  },
  {
    "id": "ach_rep_100",
    "name": "青铜勋章",
    "description": "???? 100",
    "icon": "🥉",
    "category": "reputation",
    "condition_type": "reputation",
    "condition_value": 100,
    "badge_reward_id": "badge_rep_01",
    "coin_reward": 50,
    "condition_label": "???? 100"
  },
  {
    "id": "ach_rep_500",
    "name": "白银勋章",
    "description": "???? 500",
    "icon": "🥈",
    "category": "reputation",
    "condition_type": "reputation",
    "condition_value": 500,
    "badge_reward_id": "badge_rep_02",
    "coin_reward": 150,
    "condition_label": "???? 500"
  },
  {
    "id": "ach_rep_2000",
    "name": "黄金勋章",
    "description": "???? 2000",
    "icon": "🥇",
    "category": "reputation",
    "condition_type": "reputation",
    "condition_value": 2000,
    "badge_reward_id": "badge_rep_03",
    "coin_reward": 500,
    "condition_label": "???? 2000"
  }
];

export const RETIRED_BADGE_IDS = ['badge_spc_03','badge_spc_06','badge_spc_07','badge_rep_04','badge_rep_05'];

const ACHIEVEMENT_LABEL_FIXES = {
  ach_newcomer: ['\u521d\u6765\u4e4d\u5230', '\u6ce8\u518c\u6210\u529f\u540e\u81ea\u52a8\u83b7\u5f97'],
  ach_signin_7: ['\u4e03\u65e5\u8fde\u7b7e', '\u8fde\u7eed\u7b7e\u5230 7 \u5929'],
  ach_signin_30: ['\u4e09\u5341\u65e5\u8fde\u7b7e', '\u8fde\u7eed\u7b7e\u5230 30 \u5929'],
  ach_first_post: ['\u9996\u5e16\u7eaa\u5ff5', '\u53d1\u5e03\u7b2c 1 \u7bc7\u5e16\u5b50'],
  ach_100_posts: ['\u767e\u5e16\u5b97\u5e08', '\u7d2f\u8ba1\u53d1\u5e03 100 \u7bc7\u5e16\u5b50'],
  ach_1000_posts: ['\u5343\u5e16\u4f20\u8bf4', '\u7d2f\u8ba1\u53d1\u5e03 1000 \u7bc7\u5e16\u5b50'],
  ach_first_like: ['\u9996\u8d5e\u8fbe\u4eba', '\u5e16\u5b50\u6216\u8bc4\u8bba\u83b7\u5f97\u7b2c 1 \u4e2a\u8d5e'],
  ach_100_likes: ['\u767e\u8d5e\u6536\u5272', '\u7d2f\u8ba1\u83b7\u5f97 100 \u4e2a\u8d5e'],
  ach_1000_likes: ['\u5343\u8d5e\u4e4b\u661f', '\u7d2f\u8ba1\u83b7\u5f97 1000 \u4e2a\u8d5e'],
  ach_10000_likes: ['\u4e07\u8d5e\u4f20\u5947', '\u7d2f\u8ba1\u83b7\u5f97 10000 \u4e2a\u8d5e'],
  ach_first_floor: ['\u6c99\u53d1\u4e4b\u738b', '\u9996\u6b21\u62a2\u5230\u5e16\u5b50\u6c99\u53d1'],
  ach_first_comment: ['\u8bc4\u8bba\u65b0\u661f', '\u53d1\u8868\u7b2c 1 \u6761\u8bc4\u8bba'],
  ach_500_comments: ['\u8bdd\u5520\u9644\u4f53', '\u7d2f\u8ba1\u53d1\u8868 500 \u6761\u8bc4\u8bba'],
  ach_first_accepted: ['\u6700\u4f73\u7b54\u6848', '\u56de\u7b54\u88ab\u91c7\u7eb3 1 \u6b21'],
  ach_10_accepted: ['\u7b54\u7591\u4e13\u5bb6', '\u56de\u7b54\u88ab\u91c7\u7eb3 10 \u6b21'],
  ach_bounty_hunter: ['\u60ac\u8d4f\u730e\u4eba', '\u56de\u7b54\u88ab\u91c7\u7eb3\u5e76\u83b7\u5f97\u60ac\u8d4f'],
  ach_100_followers: ['\u5173\u6ce8\u7834\u767e', '\u83b7\u5f97 100 \u4f4d\u7c89\u4e1d'],
  ach_10000_followers: ['\u4e07\u4eba\u8ff7', '\u83b7\u5f97 10000 \u4f4d\u7c89\u4e1d'],
  ach_profile_complete: ['\u5b8c\u7f8e\u6863\u6848', '\u5b8c\u5584\u4e2a\u4eba\u8d44\u6599\u4e0e\u4e3b\u9875\u88c5\u626e'],
  ach_verified: ['\u5b9e\u540d\u5148\u950b', '\u5b8c\u6210\u624b\u673a\u7ed1\u5b9a\u6216\u5b9e\u540d\u8ba4\u8bc1'],
  ach_account_365: ['\u6c38\u4e45\u5c45\u6c11', '\u6ce8\u518c\u6ee1 365 \u5929'],
  ach_account_1095: ['\u4e09\u671d\u5143\u8001', '\u6ce8\u518c\u6ee1 3 \u5e74'],
  ach_night_posts: ['\u6df1\u591c\u6d3b\u8dc3', '\u51cc\u6668 2-5 \u70b9\u53d1\u5e16 5 \u6b21'],
  ach_early_signin: ['\u65e9\u8d77\u9e1f\u513f', '6-8 \u70b9\u7b7e\u5230\u7d2f\u8ba1 30 \u6b21'],
  ach_10_blogs: ['\u535a\u5ba2\u8fbe\u4eba', '\u53d1\u5e03 10 \u7bc7\u535a\u5ba2'],
  ach_first_tip_received: ['\u6253\u8d4f\u65b0\u8d35', '\u9996\u6b21\u6536\u5230\u6253\u8d4f'],
  ach_10000_tip_received: ['\u8d22\u6e90\u5e7f\u8fdb', '\u7d2f\u8ba1\u6536\u5230 10000 \u8bba\u575b\u5e01\u6253\u8d4f'],
  ach_5000_tip_sent: ['\u6177\u6168\u89e3\u56ca', '\u7d2f\u8ba1\u6253\u8d4f\u522b\u4eba 5000 \u8bba\u575b\u5e01'],
  ach_5_five_star: ['\u4e94\u661f\u597d\u8bc4', '\u83b7\u5f97 5 \u6b21\u6ee1\u5206\u8bc4\u5206'],
  ach_5_reports: ['\u4e3e\u62a5\u536b\u58eb', '\u6709\u6548\u4e3e\u62a5\u88ab\u91c7\u7eb3 5 \u6b21'],
  ach_rep_100: ['\u9752\u94dc\u52cb\u7ae0', '\u58f0\u671b\u8fbe\u5230 100'],
  ach_rep_500: ['\u767d\u94f6\u52cb\u7ae0', '\u58f0\u671b\u8fbe\u5230 500'],
  ach_rep_2000: ['\u9ec4\u91d1\u52cb\u7ae0', '\u58f0\u671b\u8fbe\u5230 2000'],
};

for (const badge of BADGE_CATALOG) {
  if (badge.id === 'badge_ach_013') badge.name = '\u8bdd\u5520\u9644\u4f53';
}

for (const achievement of ACHIEVEMENT_CATALOG) {
  const fix = ACHIEVEMENT_LABEL_FIXES[achievement.id];
  if (!fix) continue;
  achievement.name = fix[0];
  achievement.description = fix[1];
  achievement.condition_label = fix[1];
}
